### ISSUE TITLE
Event handlers

### ISSUE THREAD

**Issue by pavlosgi** [purescript-web/purescript-web-socket#4]
Are the functions allowing attaching callbacks to various operations of the WebSocket missing?
I could write my own foreign function to do it given I have the WebSocket at hand but I was curious if this is something that was forgotten or whether there is a way to do it within the current library.

**Comment by garyb** [comment]
You mean the ability to `addEventListener`, and so on?

You can do that with what's here and the dependencies it pulls in - you need to cast the socket with `toEventTarget`, and then you can use `Web.Event.EventTarget.addEventListener`. That's the pattern in general for the web libraries, every type should have cast functions to each of the interfaces it supports.

**Comment by pavlosgi** [comment]
Thank you very much!
